#!/bin/bash
set -e

SYNC_TYPE="git"
URL=""
NAME=""
VALID_ARGS=$(getopt -o h,S: --long help,sync-type "$@")

eval set -- "$VALID_ARGS"
while [ : ]; do
    case "$1" in
    -S | --sync-type)
        shift
        SYNC_TYPE=$1
        shift
        ;;
    --)
        shift;
        break
        ;;
    *)
        echo "Invalid argument: $1"
        exit 1
        ;;
    esac
done

NAME=$1
URL=$2

eselect repository add NAME SYNC_TYPE URL
emaint sync -r NAME