#!/bin/bash
set -e
emerge --update --newuse --changed-use --deep --with-bdeps=y --backtrack=3000 --autounmask-write --autounmask-backtrack=y --fail-clean=n @world
emerge --depclean
eclean-dist --deep
eclean-pkg --deep
eix-update
