#!/bin/bash
set -e
emerge -e --changed-use --with-bdeps=y --update --newuse --deep --autounmask-write --autounmask-backtrack=y --fail-clean=y @world
emerge --depclean
eclean-dist --deep
eclean-pkg --deep
eix-update
